#ifndef LUANDARRAY_MULTIARRAY_LNCONF_H_
#define LUANDARRAY_MULTIARRAY_LNCONF_H_

#define LN_VERSION "1.0.0"
#define LN_V1_0_0

#define LN_MAX_DIMENSIONS 32

#define NDARRAY_USERDATA_NAME "ndarray"

#endif /* LUANDARRAY_MULTIARRAY_LNCONF_H_ */